### ISSUE TITLE
How can I define custom typescript type for parsed data?

### ISSUE THREAD

**Issue by danechitoaie** [LongTengDao/j-toml#12]
I'm trying to use the following code:

```
TOML.parse<{ a: string; b: string }>(tomlSource, {
    joiner: "\n",
    bigint: false,
});
```

but this give the following error:

> Argument of type '{ joiner: string; bigint: false; }' is not assignable to parameter of type '{ joiner?: string | undefined; bigint?: number | boolean | undefined; x: TagProcessor<{ a: string; b: string; }> | ({ readonly tag: TagProcessor<{ a: string; b: string; }>; readonly null?: boolean | undefined; } & TypeAgnosticOptions); }'.
  Property 'x' is missing in type '{ joiner: string; bigint: false; }' but required in type '{ joiner?: string | undefined; bigint?: number | boolean | undefined; x: TagProcessor<{ a: string; b: string; }> | ({ readonly tag: TagProcessor<{ a: string; b: string; }>; readonly null?: boolean | undefined; } & TypeAgnosticOptions); }'.ts(2345)
index.d.ts(25, 194): 'x' is declared here.

So it asks me to define `x: TagProcessor<{ a: string; b: string; }>`.
What is this?

Thanks.

**Comment by LongTengDao** [comment]
`TOML.parse` does not support argumentType, please use `as` (which is the actual behaviour for a parser program -- it does not know the source, and can not help you to make type checking):

```ts
TOML.parse(tomlSource, {
    joiner: "\n",
    bigint: false,
}) as { a: string; b: string };
```

If you need a real type check, you may need a assert function:

```ts
const root = TOML.parse(tomlSource, {
    joiner: "\n",
    bigint: false,
});

function assertAB (value :{ [name :string] :unknown }) :assert value is { a: string; b: string } {
    if ( typeof value.a!=='string' ) { throw TypeError('...'); }
    if ( typeof value.b!=='string' ) { throw TypeError('...'); }
}
assertAB(root);
```
