### ISSUE TITLE
[Feature] Option to use double quotes for strings

### ISSUE THREAD

**Issue by ajboni** [LongTengDao/j-toml#14]
It would be really nice to have an option to use double quotes instead of single quotes for strings.

```js
test("quotes", () => {
  const obj = toml.parse('title = "test"', { joiner: "\n" });
  const out = toml.stringify(obj, { newline: "\n", T: " " });
  expect(out).toEqual('title = "test"');
});
```

```diff
- title = "test"
+ title = 'test'
```

**Comment by LongTengDao** [comment]
@ajboni Now v1.25.0 is released, `toml.parse('title = "test"', { joiner: "\n", x: { literal: true } })` may help. Welcome to foretaste, and give any feedback.
