### ISSUE TITLE
Logical nullish assignment (??=) is not supported in Node <15

### ISSUE THREAD

**Issue by Vinnl** [LongTengDao/j-toml#16]
I just upgraded from 1.12.2 to 1.26.0, and now trying to run it in Node I get:

```
    /home/...snip.../node_modules/@ltd/j-toml/index.js:1779
    const commentFor = (key        )         => KEYS[key] ??= Symbol$1(key);
                                                          ^^^

    SyntaxError: Unexpected token '??='
```

This was using Node 14; apparently [`'??=` was only added in Node 15](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment#browser_compatibility).

**Comment by LongTengDao** [comment]
I remove `??=` in 1.27.0 (and checked there are no other syntax need Node 15+ by the way ;)
