### ISSUE TITLE
Cannot use with Cypress - requires es2019 or lower?

### ISSUE THREAD

**Issue by ShadowLNC** [LongTengDao/j-toml#23]
Hi, thanks for writing this library!

When I try to use this in Cypress, I get an error very similar to #1 

Here are the commands I run (MCVE):
```
cd $(mktemp -d)
npm init -y
# First time install may take a long time as it caches binaries
npm install cypress @ltd/j-toml
mkdir -p cypress/e2e

cat <<EOF > cypress.config.js
const { defineConfig } = require('cypress')
module.exports = defineConfig({e2e: { setupNodeEvents(on, config) {} , video: false, supportFile: false } })
EOF

cat <<EOF > cypress/e2e/test.cy.js
import TOML from "@ltd/j-toml";
const table = TOML.parse("", 1.0, "\n");
EOF

./node_modules/.bin/cypress run
```

I get:

```
Error: Webpack Compilation Error
./node_modules/@ltd/j-toml/index.js 629:28
Module parse failed: Unexpected token (629:28)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class mark {
>                        lineIndex = lineIndex;
|                        type                                                                                           ;
|                        restColumn        ;
```

I tried commenting out the 3 lines after `class mark {` and this shifted the error elsewhere, then there is some nullish coalescing (`??` operator). It looks like index.js in `j-toml` is built with a newer syntax than whatever is supported by Cypress.

[This comment](https://github.com/cypress-io/cypress/issues/16914#issuecomment-1179996139) suggests that it only supports `es2019` - is it possible to build `j-toml` to target `es2019` please?

**Comment by LongTengDao** [comment]
According to <https://github.com/tc39/proposals/blob/main/finished-proposals.md>, es2020+ features used in `@ltd/j-toml` include:

| es | feature |
|---|---|
| 2020 | `BigInt` |
| 2020 | `?.` |
| 2020 | `??` |
| 2022 | Class Fields |

It's possible to avoid to using them in syntax level, but `@ltd/j-toml` can't work wholy without bigint, which can not be polyfilled.

But that can be skipped if users don't need. The main question is, in <https://github.com/LongTengDao/j-toml/issues/16>, I try to support es syntax as low as Node 14 (which already to old in my mind), I just wonder why Cypress can't support es2020+ syntax. I can remove es2020+ syntax features, but someday, it maybe es3... That's awful.

I need some time to finish removing them. During that, welcome to give me some knowledge about people's need for compatibility nowadays. @ShadowLNC

**Comment by LongTengDao** [comment]
I am not familiar with Cypress. But after reading the link you given (<https://github.com/cypress-io/cypress/issues/16914>), I think it maybe a problem not related to Cypress, but Webpack es version config?
