### ISSUE TITLE
What does `.Error` mean in `import Error from '.Error'`?

### ISSUE THREAD

**Issue by ilyaigpetrov** [LongTengDao/j-toml#3]
Hello.
I've never seen such import declaration: `import Error from '.Error';`.
Why does it start with a dot?
What behavior should I expect from this notation?
Please, share a link to some article about this declaration.

Thank you,
Ilya.

**Comment by LongTengDao** [comment]
It seems you are using `.j-toml.js` for packing.

**`j-toml.js` edition (without start dot in filename) is the format that people usually use for the time being, you can use that for simplicity.**

---

`.j-toml.js` tool support is currently not published for public, but I can explain ahead.

For example, `Object.prototype.hasOwnProperty` is slow and mutable, so I write `const hasOwnProperty = Object.prototype.hasOwnProperty` instead in almost all project.

But that has a problem, if my downstream project packed a lot of upstream packages, then here will be a lot of repeating of same thing. So in `.j-toml.js` edition, I remained all reference as `import hasOwnProperty from '.Object.prototype.hasOwnProperty';` style. Module ID starts with `.` means that's a global variable.

`'.Error'` is the same. That also helps for avoiding accidental global variables reference.

**Comment by ilyaigpetrov** [comment]
> .j-toml.js tool support is currently not published for public[...]

So I can't reproduce the build and verify the dist package. Without verification the usage of your code is risky.
Also I would like to work with some popular module bundler (rollup, webpack) because this way it will be easier to verify your code.

Not that I verify every npm package with sources, I almost never do it, but I feel more trust to packages that can be verified by a community.

**Comment by LongTengDao** [comment]
Of cause! That's necessary.

In fact the bundler tool I use is a custom edition rollup (approximate rollup + dot module plugin + terser).

I just have too many package in publishing process, including bundler tool. People won't accept what you worried, me too.

Thank you for communication!

**Comment by LongTengDao** [comment]
I found an easy temporary way to ensure the dist safe.

1. The dist code only includes one `require('fs').readFileSync` in the `parse`, which only called for `sourcePath` parameter
2. `parse` is not called in the dist self
3. There is no any more `require` or `import` called
4. There is no any net API called
5. There is no any `eval` reference, and no any `Function` reference, and only two `constructor` property access which only lead to `delete` behaviour.

https://github.com/LongTengDao/j-toml/blob/ebcd61c6910d1527d2f1b7d503a3d18089a6ff96/dist/NPM/index.js#L1939

https://github.com/LongTengDao/j-toml/blob/ebcd61c6910d1527d2f1b7d503a3d18089a6ff96/dist/NPM/index.js#L384

https://github.com/LongTengDao/j-toml/blob/ebcd61c6910d1527d2f1b7d503a3d18089a6ff96/dist/NPM/index.js#L494

@ilyaigpetrov Hope this would help.

**Comment by ilyaigpetrov** [comment]
If some other developer can't fork your project and develop/build it himself with the same provided toolset (for the equal productivity) as you then I doubt it should be called "Open Source". For the same reason we don't call obfuscated sources "Open Source" because editing obfuscated code can't compete in productivity with editing original code. I'm not a guru of open source philosophy, I can mistake, but that's how I get it.
