### ISSUE TITLE
v1.16.0 breaks bundled javascript

### ISSUE THREAD

**Issue by bglw** [LongTengDao/j-toml#8]
Hello 👋

v1.16.0 introduces a static fs import in [parse/.ts:8](https://github.com/LongTengDao/j-toml/commit/f6f338a55fbbc1ef919ff37c374ee840f0f7498a#diff-7c61e1825e89a0106249629ad9d43396673b10de598ac12810a229fd466c77b4R8). This breaks any frontend bundling that isn't stubbing out node libraries. In a default esbuild run I now get:
```
 > node_modules/@ltd/j-toml/index.mjs:1:32: error: Could not resolve "fs" (use "platform: 'node'" when building for node)
    1 │ import { readFileSync } from 'fs';
```

Could this be changed to something like a dynamic import behind a try? Loosely something like:
```
let fs = { readFileSync: () => { throw Error("readFileSync unsupported outside of node"} } };
try {
    fs = await import('fs');
}
```

Or something behind a platform flag.

**Comment by LongTengDao** [comment]
I see. Before fixing, may I ask, which file do you bundle in fact, `dist/ESM/j-toml.js`, or `dist/NPM/index.mjs`?

**Comment by LongTengDao** [comment]
I see.

> Or something behind a platform flag.

How?

**Comment by bglw** [comment]
Hmm, I was under the impression there was a supported way to check but it doesn't look like there is.

[The checks in the browser-or-node package](https://github.com/flexdinesh/browser-or-node/blob/master/src/index.js) look simple enough to re-implement, though.

**Comment by bglw** [comment]
In saying that, I don't know if other packages provide any workaround for this, so maybe it's idiomatic for users to fix this in their bundler configuration... 🤔

**Comment by LongTengDao** [comment]
I don't know any way good enough. I removed the statically module loading, hope that would help?

**Comment by bglw** [comment]
Ah, that's perfect. Thanks a tonne! 😄  🎉
