### ISSUE TITLE
use in browser

### ISSUE THREAD

**Issue by tans** [LongTengDao/j-toml#9]
need to use toml in browser,  so how to build a version for the browser

**Comment by LongTengDao** [comment]
UMD edtion could be easily transform from `ESM/j-toml.js`. And I released v1.20.0 which contains UMD edtion just now:


| Edition                    | Description                                                                                               |
|:---------------------------|:----------------------------------------------------------------------------------------------------------|
| `UMD/j-toml.js`            | The edition built as [`UMD`][UMD-en] (width source mapper inline).                                        |
| `UMD/j-toml.min.js`        | The edition built as minified [`UMD`][UMD-en].                                                            |
| `UMD/j-toml.min.js.gz`     | The gzip file (only if smaller) of the edition built as minified [`UMD`][UMD-en].                         |

Hope that would help
